// Package registry holds the embedded provider registry: the static provider
// catalog loaded once at boot.
//
// @file      internal/registry/capability_resolve_test.go
// @for       The corpus test that pins the capability resolver against the
//
//	reference's own answers.
//
// @uses      testing, encoding/json, os, path/filepath, internal/registry.
// @reason    SPEC-API-001 §7.6 offers `?capability=vision|tools`, and §7.8
//
//	refuses a vision adapter whose models cannot read images. The two
//	consumers read one resolver, and the resolver is checked against a
//	corpus generated by running the reference's own function, so a
//	disagreement names the model that differs instead of proving the
//	port agrees with a second copy of itself.
//
//	This test reads the REAL embedded registry's model ids (through the
//	corpus, which is generated from them), which is what draft 017 §4.4
//	requires: the fixture-based tests it replaces wrote "vision" into
//	their own data and could not fail.
//
// @author    Dodi Rusmana <rusmanadodi@kentangtech.com>
// @layer     config
// @stability experimental
// @since     2026-09-23
package registry

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// capabilityCorpus is the generated file's shape. It is decoded here rather
// than in a shared helper because exactly one test reads it.
type capabilityCorpus struct {
	Revision string `json:"revision"`
	Source   string `json:"source"`
	Entries  []struct {
		Provider           string `json:"provider"`
		Model              string `json:"model"`
		Vision             bool   `json:"vision"`
		Tools              bool   `json:"tools"`
		Reasoning          bool   `json:"reasoning"`
		ThinkingFormat     string `json:"thinking_format"`
		ThinkingCanDisable bool   `json:"thinking_can_disable"`
	} `json:"entries"`
}

func loadCapabilityCorpus(t *testing.T) capabilityCorpus {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "capabilities_corpus.json"))
	if err != nil {
		t.Fatalf("reading the corpus: %v", err)
	}
	var corpus capabilityCorpus
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("decoding the corpus: %v", err)
	}
	if len(corpus.Entries) == 0 {
		t.Fatal("the corpus is empty; regenerate it with tools/capability-gen.mjs")
	}
	return corpus
}

// TestCapabilities_MatchesTheReferenceCorpus is the pin: every model the
// embedded registry declares, answered the way the reference answers it. The
// reasoning trio is compared only when the model reasons, because a
// non-reasoning row's format and can-disable fields are the reference's floor
// and carry no meaning.
func TestCapabilities_MatchesTheReferenceCorpus(t *testing.T) {
	corpus := loadCapabilityCorpus(t)
	vision, noTools, reasoning := 0, 0, 0
	for _, entry := range corpus.Entries {
		if entry.Vision {
			vision++
		}
		if !entry.Tools {
			noTools++
		}
		if entry.Reasoning {
			reasoning++
		}
		got := Capabilities(entry.Provider, entry.Model)
		if got.Vision != entry.Vision || got.Tools != entry.Tools {
			t.Fatalf("Capabilities(%q, %q) = {vision:%v tools:%v}, the reference says {vision:%v tools:%v} (corpus revision %s)",
				entry.Provider, entry.Model, got.Vision, got.Tools, entry.Vision, entry.Tools, corpus.Revision)
		}
		if got.Reasoning != entry.Reasoning {
			t.Fatalf("Capabilities(%q, %q).Reasoning = %v, the reference says %v (corpus revision %s)",
				entry.Provider, entry.Model, got.Reasoning, entry.Reasoning, corpus.Revision)
		}
		if !entry.Reasoning {
			continue
		}
		if got.ThinkingFormat != entry.ThinkingFormat || got.CanDisable != entry.ThinkingCanDisable {
			t.Fatalf("Capabilities(%q, %q) = {format:%q canDisable:%v}, the reference says {format:%q canDisable:%v} (corpus revision %s)",
				entry.Provider, entry.Model, got.ThinkingFormat, got.CanDisable, entry.ThinkingFormat, entry.ThinkingCanDisable, corpus.Revision)
		}
	}
	// The counts guard the corpus itself: a corpus that answered the floor for
	// every row would pass a resolver that also answered the floor, which is
	// exactly the state draft 017 §4.4 measured and this pass exists to fix.
	if vision == 0 {
		t.Fatalf("the corpus reports no vision-capable model across %d rows; the corpus is wrong, not the resolver", len(corpus.Entries))
	}
	if noTools == 0 {
		t.Fatalf("the corpus reports no model without tool calling across %d rows; the tools rule would be untested", len(corpus.Entries))
	}
	if reasoning == 0 {
		t.Fatalf("the corpus reports no reasoning model across %d rows; the thinking tables would be untested", len(corpus.Entries))
	}
	t.Logf("pinned %d rows against %s: %d vision, %d without tools, %d reasoning",
		len(corpus.Entries), corpus.Revision, vision, noTools, reasoning)
}

// TestCapabilities_ProviderLayerIsLoadBearing pins the fact that made the
// provider layer part of the port: the reference consults PROVIDER_CAPABILITIES
// before its exact and pattern layers (capabilities.js:586-590), and at the
// pinned revision that layer changes the vision answer for models the embedded
// registry declares. The first version of this port omitted the layer because
// the older pin measured zero such rows; the corpus now proves the opposite, so
// the test asserts the layer is reached rather than that it is harmless.
//
// The list is deliberately small and named: these are the rows that fail if the
// layer is dropped, so a reader sees exactly what the layer buys.
func TestCapabilities_ProviderLayerIsLoadBearing(t *testing.T) {
	cases := []struct {
		provider string
		model    string
		want     bool
	}{
		// codebuddy-cn reads images on every model it proxies, including the
		// ones whose family pattern would answer false.
		{provider: "codebuddy-cn", model: "deepseek-v4-pro", want: true},
		{provider: "codebuddy-cn", model: "glm-5.2", want: true},
		// nvidia's MiniMax M3 is multimodal while the same family under the
		// commandcode wire is text-only, so the answer depends on the provider.
		{provider: "nvidia", model: "minimaxai/minimax-m3", want: true},
		{provider: "commandcode", model: "MiniMaxAI/MiniMax-M2.5", want: false},
		// The name heuristic must not rescue it: M2.5 carries no modality word,
		// and the denylist is consulted before the pattern table either way.
		{provider: "commandcode", model: "Qwen/Qwen3.7-Max", want: false},
	}
	for _, tc := range cases {
		t.Run(tc.provider+"/"+tc.model, func(t *testing.T) {
			got := Capabilities(tc.provider, tc.model)
			if got.Vision != tc.want {
				t.Fatalf("Capabilities(%q, %q).Vision = %v, want %v; the provider layer is load-bearing at this revision",
					tc.provider, tc.model, got.Vision, tc.want)
			}
		})
	}
}

// TestCapabilities_BoundaryInputs covers the inputs the corpus cannot carry: an
// absent model, whitespace, a vendor-prefixed id, an id that is itself a path,
// and an id nothing knows.
func TestCapabilities_BoundaryInputs(t *testing.T) {
	// Every floor answer carries CanDisable true, because the reference's floor
	// lets a model turn thinking off and only a table row can say otherwise.
	floor := CapabilitySet{Vision: false, Tools: true, CanDisable: true}
	cases := []struct {
		name     string
		provider string
		model    string
		want     CapabilitySet
	}{
		{"an empty model answers the floor", "openai", "", floor},
		{"whitespace is trimmed, not matched", "openai", "   ", floor},
		{
			name: "a vendor prefix is stripped before matching", provider: "openrouter", model: "anthropic/claude-opus-4-8",
			want: CapabilitySet{Vision: true, Tools: true, Reasoning: true, ThinkingFormat: "claude-adaptive", CanDisable: true},
		},
		{"a model id may itself be a path", "", "vendor/family/model", floor},
		{"an image model declares no tools", "openai", "gpt-image-1", CapabilitySet{Vision: false, Tools: false, CanDisable: true}},
		{"an unknown id answers the floor", "", "totally-unknown-9000", floor},
		{"the match ignores case", "openai", "GPT-4O", CapabilitySet{Vision: true, Tools: true, CanDisable: true}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := Capabilities(tc.provider, tc.model); got != tc.want {
				t.Fatalf("Capabilities(%q, %q) = %+v, want %+v", tc.provider, tc.model, got, tc.want)
			}
		})
	}
}

// TestCapabilitySet_Has covers the membership rule the catalog filter uses: the
// two names it resolves, a media string it does not, and an unknown name.
func TestCapabilitySet_Has(t *testing.T) {
	cases := []struct {
		name string
		set  CapabilitySet
		want map[string]bool
	}{
		{
			name: "a vision model answers vision and tools",
			set:  CapabilitySet{Vision: true, Tools: true},
			want: map[string]bool{"vision": true, "tools": true, "edit": false, "": false, "Vision": true},
		},
		{
			name: "a padded name is trimmed before the switch",
			set:  CapabilitySet{Vision: true, Tools: true},
			want: map[string]bool{"  tools  ": true, "\tvision\n": true},
		},
		{
			name: "a floor model answers tools only",
			set:  CapabilitySet{Vision: false, Tools: true},
			want: map[string]bool{"vision": false, "tools": true, "edit": false},
		},
		{
			name: "an image model answers neither",
			set:  CapabilitySet{Vision: false, Tools: false},
			want: map[string]bool{"vision": false, "tools": false},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			for name, want := range tc.want {
				if got := tc.set.Has(name); got != want {
					t.Fatalf("CapabilitySet{%+v}.Has(%q) = %v, want %v", tc.set, name, got, want)
				}
			}
		})
	}
}
