// Package registry holds the embedded provider registry: the static provider
// catalog loaded once at boot.
//
// @file      internal/registry/capability_resolve_test.go
// @for       The corpus test that pins the capability resolver against the
//
//	reference's own answers.
//
// @uses      testing, encoding/json, os, path/filepath, internal/registry.
// @reason    SPEC-API-001 §7.6 offers `?capability=vision|tools`, and §7.8
//
//	refuses a vision adapter whose models cannot read images. The two
//	consumers read one resolver, and the resolver is checked against a
//	corpus generated by running the reference's own function, so a
//	disagreement names the model that differs instead of proving the
//	port agrees with a second copy of itself.
//
//	This test reads the REAL embedded registry's model ids (through the
//	corpus, which is generated from them), which is what draft 017 §4.4
//	requires: the fixture-based tests it replaces wrote "vision" into
//	their own data and could not fail.
//
// @author    Dodi Rusmana <rusmanadodi@kentangtech.com>
// @layer     config
// @stability experimental
// @since     2026-09-23
package registry

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// capabilityCorpus is the generated file's shape. It is decoded here rather
// than in a shared helper because exactly one test reads it. The range's bounds
// are pointers so a corpus row carrying a null bound fails loudly rather than
// reading as zero: the resolver's own shape has no null.
type capabilityCorpus struct {
	Revision string `json:"revision"`
	Source   string `json:"source"`
	Entries  []struct {
		Provider           string `json:"provider"`
		Model              string `json:"model"`
		Vision             bool   `json:"vision"`
		Tools              bool   `json:"tools"`
		Reasoning          bool   `json:"reasoning"`
		ThinkingFormat     string `json:"thinking_format"`
		ThinkingCanDisable bool   `json:"thinking_can_disable"`
		ThinkingRange      *struct {
			Min *int `json:"min"`
			Max *int `json:"max"`
		} `json:"thinking_range"`
		ThinkingEffortSupported bool `json:"thinking_effort_supported"`
	} `json:"entries"`
}

func loadCapabilityCorpus(t *testing.T) capabilityCorpus {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "capabilities_corpus.json"))
	if err != nil {
		t.Fatalf("reading the corpus: %v", err)
	}
	var corpus capabilityCorpus
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("decoding the corpus: %v", err)
	}
	if len(corpus.Entries) == 0 {
		t.Fatal("the corpus is empty; regenerate it with tools/capability-gen.mjs")
	}
	return corpus
}

// TestCapabilities_MatchesTheReferenceCorpus is the pin: every model the
// embedded registry declares, answered the way the reference answers it. The
// reasoning trio is compared only when the model reasons, because a
// non-reasoning row's format and can-disable fields are the reference's floor
// and carry no meaning.
func TestCapabilities_MatchesTheReferenceCorpus(t *testing.T) {
	corpus := loadCapabilityCorpus(t)
	vision, noTools, reasoning, ranges, efforts := 0, 0, 0, 0, 0
	for _, entry := range corpus.Entries {
		if entry.Vision {
			vision++
		}
		if !entry.Tools {
			noTools++
		}
		if entry.Reasoning {
			reasoning++
		}
		if entry.ThinkingRange != nil {
			ranges++
		}
		if entry.ThinkingEffortSupported {
			efforts++
		}
		got := Capabilities(entry.Provider, entry.Model)
		if got.Vision != entry.Vision || got.Tools != entry.Tools {
			t.Fatalf("Capabilities(%q, %q) = {vision:%v tools:%v}, the reference says {vision:%v tools:%v} (corpus revision %s)",
				entry.Provider, entry.Model, got.Vision, got.Tools, entry.Vision, entry.Tools, corpus.Revision)
		}
		if got.Reasoning != entry.Reasoning {
			t.Fatalf("Capabilities(%q, %q).Reasoning = %v, the reference says %v (corpus revision %s)",
				entry.Provider, entry.Model, got.Reasoning, entry.Reasoning, corpus.Revision)
		}
		if !entry.Reasoning {
			continue
		}
		if got.ThinkingFormat != entry.ThinkingFormat || got.CanDisable != entry.ThinkingCanDisable {
			t.Fatalf("Capabilities(%q, %q) = {format:%q canDisable:%v}, the reference says {format:%q canDisable:%v} (corpus revision %s)",
				entry.Provider, entry.Model, got.ThinkingFormat, got.CanDisable, entry.ThinkingFormat, entry.ThinkingCanDisable, corpus.Revision)
		}
		if entry.ThinkingRange != nil && (entry.ThinkingRange.Min == nil || entry.ThinkingRange.Max == nil) {
			t.Fatalf("corpus row %s/%s carries a range with a null bound; the resolver's shape has no null, so the generator must widen it before this row can be pinned",
				entry.Provider, entry.Model)
		}
		wantRange := rangeFromCorpus(entry.ThinkingRange)
		if !sameThinkingRange(got.ThinkingRange, wantRange) {
			t.Fatalf("Capabilities(%q, %q).ThinkingRange = %+v, the reference says %+v (corpus revision %s)",
				entry.Provider, entry.Model, got.ThinkingRange, wantRange, corpus.Revision)
		}
		if got.EffortSupported != entry.ThinkingEffortSupported {
			t.Fatalf("Capabilities(%q, %q).EffortSupported = %v, the reference says %v (corpus revision %s)",
				entry.Provider, entry.Model, got.EffortSupported, entry.ThinkingEffortSupported, corpus.Revision)
		}
	}
	// The counts guard the corpus itself: a corpus that answered the floor for
	// every row would pass a resolver that also answered the floor, which is
	// exactly the state draft 017 §4.4 measured and this pass exists to fix.
	if vision == 0 {
		t.Fatalf("the corpus reports no vision-capable model across %d rows; the corpus is wrong, not the resolver", len(corpus.Entries))
	}
	if noTools == 0 {
		t.Fatalf("the corpus reports no model without tool calling across %d rows; the tools rule would be untested", len(corpus.Entries))
	}
	if reasoning == 0 {
		t.Fatalf("the corpus reports no reasoning model across %d rows; the thinking tables would be untested", len(corpus.Entries))
	}
	if ranges == 0 || efforts == 0 {
		t.Fatalf("the corpus reports %d ranges and %d effort-supporting rows across %d entries; both rules would be untested",
			ranges, efforts, len(corpus.Entries))
	}
	t.Logf("pinned %d rows against %s: %d vision, %d without tools, %d reasoning, %d with a budget range, %d effort-supporting",
		len(corpus.Entries), corpus.Revision, vision, noTools, reasoning, ranges, efforts)
}

// rangeFromCorpus turns a corpus row's optional range into the resolver's own
// shape, so the comparison is one helper rather than a branch per assertion.
func rangeFromCorpus(in *struct {
	Min *int `json:"min"`
	Max *int `json:"max"`
}) *ThinkingRange {
	if in == nil || in.Min == nil || in.Max == nil {
		return nil
	}
	return &ThinkingRange{Min: *in.Min, Max: *in.Max}
}

// sameThinkingRange compares two optional ranges by value, because the
// resolver's answer is built per call and a pointer comparison would only ever
// prove two allocations differ.
func sameThinkingRange(got, want *ThinkingRange) bool {
	if got == nil || want == nil {
		return got == nil && want == nil
	}
	return *got == *want
}
