// Package registry holds the embedded provider registry: the static provider
// catalog loaded once at boot.
//
// @file      internal/registry/capability_test.go
// @for       Tests for the ported vision predicate.
// @uses      testing.
// @reason    SPEC-API-001 §7.8 refuses a vision adapter whose models cannot read
//
//	images, so a wrong answer here either blocks a working configuration
//	or admits one that fails upstream on the first image. The expectations
//	in this file were generated by running the reference's own
//	getCapabilitiesForModel over the same ids, so the test proves the port
//	agrees with capabilities.js rather than agreeing with itself.
//
// @author    Dodi Rusmana <rusmanadodi@kentangtech.com>
// @layer     config
// @stability experimental
// @since     2026-09-18
package registry

import "testing"

// TestVisionCapable_MatchesTheReference pins every rule boundary: each family,
// the variants that shadow their family, and the two exact-id exceptions.
func TestVisionCapable_MatchesTheReference(t *testing.T) {
	cases := []struct {
		id   string
		want bool
	}{
		// Claude reads images across the family.
		{"claude-opus-4.6", true},
		{"claude-sonnet-4-6", true},
		{"claude-3-5-sonnet-20241022", true},
		{"claude-haiku-4-5", true},

		// Gemini, Gemma, and the image model.
		{"gemini-2.5-pro", true},
		{"gemini-3-pro-preview", true},
		{"gemini-1.5-flash", true},
		{"gemma-3-27b-it", true},
		{"nanobanana-pro", true},

		// OpenAI: the image and codex variants shadow the family rule.
		{"gpt-5", true},
		{"gpt-5-codex", false},
		{"gpt-5-image", false},
		{"gpt-4o", true},
		{"gpt-4.1", true},
		{"gpt-4-turbo", true},
		{"gpt-4", false},
		{"gpt-3.5-turbo", false},
		{"gpt-oss-120b", false},

		// The o-series, where o1-mini is the text-only member.
		{"o1", true},
		{"o1-mini", false},
		{"o3-mini", true},
		{"o4-mini", true},

		// Grok, same shadowing shape.
		{"grok-4", true},
		{"grok-3", true},
		{"grok-code-fast-1", false},
		{"grok-2-image-1212", false},

		// Qwen: only the vision, max, and plus variants read images.
		{"qwen3-max", true},
		{"qwen-vl-max", true},
		{"qwen-plus", true},
		{"qwen-235b", false},
		{"qwen3-coder", false},
		{"qwq-32b", false},
		{"qwen-turbo", false},

		// Kimi K2 reads images; the rest of the family does not.
		{"kimi-k2-thinking", true},
		{"kimi-k2.7-code", true},
		{"kimi-latest", false},

		// GLM: the exact-id exception, and the family that does not read images.
		{"glm-4.6v", true},
		{"glm-4.6", false},
		{"glm-5", false},

		// Families the reference leaves text-only, with the two members the
		// reference's own pattern table now answers true: MiniMax M2.5+ and M3
		// read images while the older M2 does not, which is the `*minimax-m3*`
		// and `*minimax-m2.7*` rows in the ported table.
		{"deepseek-chat", false},
		{"deepseek-reasoner", false},
		{"minimax-m2", false},
		{"minimax-m2.5", true},
		{"minimax-m3", true},

		// MiMo and Llama-4 read images.
		{"mimo-v2.5", true},
		{"mimo-omni", true},
		{"mimo-7b", true},
		{"llama-4-scout", true},
		{"llama-3.3-70b", false},

		// Mistral and Cohere, each with one vision variant.
		{"mistral-large-2411", true},
		{"mistral-small-latest", false},
		{"codestral-2501", false},
		{"command-a-vision-07-2025", true},
		{"command-r-plus", false},

		// Search and thinking families carry no vision.
		{"sonar-pro", false},
		{"perplexity-sonnet", false},
		{"hunyuan-t1", false},
		{"step-2-16k", false},
		{"nemotron-70b", false},
		{"ling-flash-2.0", false},

		// The registry's own alias, and an id nothing knows.
		{"vision-model", true},
		{"coder-model", false},
		{"unknown-model", false},
	}
	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			if got := VisionCapable(tc.id); got != tc.want {
				t.Fatalf("VisionCapable(%q) = %v, want %v", tc.id, got, tc.want)
			}
		})
	}
}

// TestVisionCapable_IgnoresCaseAndSpace covers the normalization, so a registry
// id and a hand-typed one cannot disagree.
func TestVisionCapable_IgnoresCaseAndSpace(t *testing.T) {
	for _, id := range []string{"gpt-4o", "GPT-4O", "  gpt-4o  ", "Gpt-4O"} {
		if !VisionCapable(id) {
			t.Fatalf("VisionCapable(%q) = false, want true", id)
		}
	}
}

// TestMatchesGlob covers the matcher on its own, including the cases the pattern
// table does not reach: an empty pattern, a literal, and a repeat.
func TestMatchesGlob(t *testing.T) {
	cases := []struct {
		name    string
		pattern string
		value   string
		want    bool
	}{
		{name: "a bare star matches anything", pattern: "*", value: "anything", want: true},
		{name: "an empty value matches a bare star", pattern: "*", value: "", want: true},
		{name: "a literal must match exactly", pattern: "gpt-4o", value: "gpt-4o", want: true},
		{name: "a literal does not match a prefix", pattern: "gpt-4o", value: "gpt-4o-mini", want: false},
		{name: "the match is anchored at the front", pattern: "4o*", value: "gpt-4o", want: false},
		{name: "the match is anchored at the end", pattern: "*4o", value: "4o-mini", want: false},
		{name: "a middle star spans a run", pattern: "*qwen*max*", value: "qwen3-max", want: true},
		{name: "a middle star needs its parts in order", pattern: "*max*qwen*", value: "qwen3-max", want: false},
		{name: "parts may not overlap", pattern: "*ab*b*", value: "ab", want: false},
		{name: "an empty pattern matches only an empty value", pattern: "", value: "", want: true},
		{name: "an empty pattern does not match a value", pattern: "", value: "x", want: false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := matchesGlob(tc.pattern, tc.value); got != tc.want {
				t.Fatalf("matchesGlob(%q, %q) = %v, want %v", tc.pattern, tc.value, got, tc.want)
			}
		})
	}
}
