// Package registry holds the embedded provider registry: the static provider
// catalog loaded once at boot.
//
// @file      internal/registry/pricing_corpus_test.go
// @for       The rate resolver checked pair-by-pair against the reference's own
//
//	answers, recorded in the generated pricing corpus.
//
// @uses      testing, encoding/json, os, path/filepath, internal/registry.
// @reason    The rate tables are a port of the reference's pricing.js, and a port
//
//	checked only against itself proves nothing. The corpus is generated by
//	running the reference's own resolver over every (provider, model)
//	pair the embedded registry declares (tools/pricing-gen.mjs), so a
//	disagreement names the exact model that differs. The formula and
//	fallback order are pinned separately in pricing_test.go, where the
//	corpus cannot isolate an arithmetic edge.
//
// @author    Dodi Rusmana <rusmanadodi@kentangtech.com>
// @layer     config
// @stability experimental
// @since     2026-09-26
package registry

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// pricingShape is one corpus token shape, as the generator recorded it.
type pricingShape struct {
	Name   string             `json:"name"`
	Tokens pricingShapeTokens `json:"tokens"`
}

// pricingShapeTokens carries the corpus's raw token fields, named as the
// reference's canonical convention names them.
type pricingShapeTokens struct {
	PromptTokens             int `json:"prompt_tokens"`
	CompletionTokens         int `json:"completion_tokens"`
	CachedTokens             int `json:"cached_tokens"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
	ReasoningTokens          int `json:"reasoning_tokens"`
}

// counts maps one corpus shape onto the token shape the formula takes, so the
// test reads the same fields the service maps from a schema.Usage.
func (s pricingShape) counts() TokenCounts {
	return TokenCounts{
		Prompt:        int64(s.Tokens.PromptTokens),
		Completion:    int64(s.Tokens.CompletionTokens),
		Cached:        int64(s.Tokens.CachedTokens),
		CacheCreation: int64(s.Tokens.CacheCreationInputTokens),
		Reasoning:     int64(s.Tokens.ReasoningTokens),
	}
}

// pricingCorpusEntry is one registry (provider, model) pair as the generator
// recorded the reference's own answers for it.
type pricingCorpusEntry struct {
	Provider string `json:"provider"`
	Model    string `json:"model"`
	Rates    struct {
		Input         *string `json:"input"`
		Output        *string `json:"output"`
		Cached        *string `json:"cached"`
		Reasoning     *string `json:"reasoning"`
		CacheCreation *string `json:"cache_creation"`
	} `json:"rates"`
	Costs map[string]string `json:"costs"`
}

// pricingCorpus is the generated file's shape: the reference's rates and costs
// for every registry pair, over the generator's fixed token shapes.
type pricingCorpus struct {
	Revision string               `json:"revision"`
	Source   string               `json:"source"`
	Shapes   []pricingShape       `json:"shapes"`
	Entries  []pricingCorpusEntry `json:"entries"`
}

func loadPricingCorpus(t *testing.T) pricingCorpus {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "pricing_corpus.json"))
	if err != nil {
		t.Fatalf("reading the corpus: %v", err)
	}
	var corpus pricingCorpus
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("decoding the corpus: %v", err)
	}
	return corpus
}

func corpusRate(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// TestPricing_MatchesTheReferenceCorpus walks every registry pair and compares
// both halves of the port to the reference's own answers: the resolved rates,
// and the cost the formula renders for each of the generator's token shapes.
// An unpriced pair must answer "not priced" here, because the reference's own
// resolver answers null there and a usage row must record zero rather than a
// guessed rate.
func TestPricing_MatchesTheReferenceCorpus(t *testing.T) {
	corpus := loadPricingCorpus(t)
	// The corpus must cover exactly the pairs the embedded registry declares:
	// the generator walks that document, so a mismatch means one side was
	// regenerated without the other, and a corpus that silently shrank would
	// stop proving anything.
	idx, err := Load()
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	pairs := 0
	for _, provider := range idx.All() {
		pairs += len(provider.Models)
	}
	if len(corpus.Entries) != pairs {
		t.Fatalf("the corpus covers %d pairs, the registry declares %d; regenerate with tools/pricing-gen.mjs",
			len(corpus.Entries), pairs)
	}
	if len(corpus.Shapes) < 3 {
		t.Fatalf("the corpus declares %d shapes; regenerate with tools/pricing-gen.mjs", len(corpus.Shapes))
	}

	for _, entry := range corpus.Entries {
		rates, priced := ResolvePricing(entry.Provider, entry.Model)
		if priced != (entry.Rates.Input != nil) {
			t.Fatalf("%s/%s: priced=%v, reference priced=%v", entry.Provider, entry.Model, priced, entry.Rates.Input != nil)
		}
		if !priced {
			if len(entry.Costs) != 0 {
				t.Fatalf("%s/%s: unpriced but the corpus carries costs", entry.Provider, entry.Model)
			}
			continue
		}
		want := Rate{
			Input:         corpusRate(entry.Rates.Input),
			Output:        corpusRate(entry.Rates.Output),
			Cached:        corpusRate(entry.Rates.Cached),
			Reasoning:     corpusRate(entry.Rates.Reasoning),
			CacheCreation: corpusRate(entry.Rates.CacheCreation),
		}
		if rates != want {
			t.Fatalf("%s/%s: rates = %+v, reference = %+v", entry.Provider, entry.Model, rates, want)
		}
		for _, shape := range corpus.Shapes {
			got := ChatCost(entry.Provider, entry.Model, shape.counts())
			if wantCost, ok := entry.Costs[shape.Name]; !ok || got != wantCost {
				t.Fatalf("%s/%s %s: cost = %s, reference = %q", entry.Provider, entry.Model, shape.Name, got, wantCost)
			}
		}
	}
}
