// Package registry holds the embedded provider registry: the static provider
// catalog loaded once at boot.
//
// @file      internal/registry/pricing_test.go
// @for       The rate resolver and the token-to-cost estimate, checked against
//
//	the reference's own answers.
//
// @uses      testing, encoding/json, os, path/filepath, internal/registry.
// @reason    The rate tables and the cost formula are a port of the reference's
//
//	pricing.js, and a port checked only against itself proves nothing. The
//	corpus is generated by running the reference's own resolver and cost
//	function over every (provider, model) pair the embedded registry
//	declares (tools/pricing-gen.mjs), so a disagreement names the exact
//	model that differs; the fallback and formula tables pin the order and
//	the arithmetic edges the corpus cannot isolate — the inclusive-prompt
//	cache split, the clamp when the cache subsets exceed the prompt, the
//	reasoning premium, and the zero answer for an unpriced model.
//
// @author    Dodi Rusmana <rusmanadodi@kentangtech.com>
// @layer     config
// @stability experimental
// @since     2026-09-23
package registry

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// pricingShape is one corpus token shape, as the generator recorded it.
type pricingShape struct {
	Name   string             `json:"name"`
	Tokens pricingShapeTokens `json:"tokens"`
}

// pricingShapeTokens carries the corpus's raw token fields, named as the
// reference's canonical convention names them.
type pricingShapeTokens struct {
	PromptTokens             int `json:"prompt_tokens"`
	CompletionTokens         int `json:"completion_tokens"`
	CachedTokens             int `json:"cached_tokens"`
	CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
	ReasoningTokens          int `json:"reasoning_tokens"`
}

// counts maps one corpus shape onto the token shape the formula takes, so the
// test reads the same fields the service maps from a schema.Usage.
func (s pricingShape) counts() TokenCounts {
	return TokenCounts{
		Prompt:        int64(s.Tokens.PromptTokens),
		Completion:    int64(s.Tokens.CompletionTokens),
		Cached:        int64(s.Tokens.CachedTokens),
		CacheCreation: int64(s.Tokens.CacheCreationInputTokens),
		Reasoning:     int64(s.Tokens.ReasoningTokens),
	}
}

// pricingCorpusEntry is one registry (provider, model) pair as the generator
// recorded the reference's own answers for it.
type pricingCorpusEntry struct {
	Provider string `json:"provider"`
	Model    string `json:"model"`
	Rates    struct {
		Input         *string `json:"input"`
		Output        *string `json:"output"`
		Cached        *string `json:"cached"`
		Reasoning     *string `json:"reasoning"`
		CacheCreation *string `json:"cache_creation"`
	} `json:"rates"`
	Costs map[string]string `json:"costs"`
}

// pricingCorpus is the generated file's shape: the reference's rates and costs
// for every registry pair, over the generator's fixed token shapes.
type pricingCorpus struct {
	Revision string               `json:"revision"`
	Source   string               `json:"source"`
	Shapes   []pricingShape       `json:"shapes"`
	Entries  []pricingCorpusEntry `json:"entries"`
}

func loadPricingCorpus(t *testing.T) pricingCorpus {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "pricing_corpus.json"))
	if err != nil {
		t.Fatalf("reading the corpus: %v", err)
	}
	var corpus pricingCorpus
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("decoding the corpus: %v", err)
	}
	return corpus
}

func corpusRate(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

// TestPricing_MatchesTheReferenceCorpus walks every registry pair and compares
// both halves of the port to the reference's own answers: the resolved rates,
// and the cost the formula renders for each of the generator's token shapes.
// An unpriced pair must answer "not priced" here, because the reference's own
// resolver answers null there and a usage row must record zero rather than a
// guessed rate.
func TestPricing_MatchesTheReferenceCorpus(t *testing.T) {
	corpus := loadPricingCorpus(t)
	if len(corpus.Entries) < 500 {
		t.Fatalf("the corpus is too small (%d entries); regenerate with tools/pricing-gen.mjs", len(corpus.Entries))
	}
	if len(corpus.Shapes) < 3 {
		t.Fatalf("the corpus declares %d shapes; regenerate with tools/pricing-gen.mjs", len(corpus.Shapes))
	}

	for _, entry := range corpus.Entries {
		rates, priced := ResolvePricing(entry.Provider, entry.Model)
		if priced != (entry.Rates.Input != nil) {
			t.Fatalf("%s/%s: priced=%v, reference priced=%v", entry.Provider, entry.Model, priced, entry.Rates.Input != nil)
		}
		if !priced {
			if len(entry.Costs) != 0 {
				t.Fatalf("%s/%s: unpriced but the corpus carries costs", entry.Provider, entry.Model)
			}
			continue
		}
		want := Rate{
			Input:         corpusRate(entry.Rates.Input),
			Output:        corpusRate(entry.Rates.Output),
			Cached:        corpusRate(entry.Rates.Cached),
			Reasoning:     corpusRate(entry.Rates.Reasoning),
			CacheCreation: corpusRate(entry.Rates.CacheCreation),
		}
		if rates != want {
			t.Fatalf("%s/%s: rates = %+v, reference = %+v", entry.Provider, entry.Model, rates, want)
		}
		for _, shape := range corpus.Shapes {
			got := ChatCost(entry.Provider, entry.Model, shape.counts())
			if wantCost, ok := entry.Costs[shape.Name]; !ok || got != wantCost {
				t.Fatalf("%s/%s %s: cost = %s, reference = %q", entry.Provider, entry.Model, shape.Name, got, wantCost)
			}
		}
	}
}

// TestPricing_FallbackChainOrder pins the resolution order: the
// provider-specific override first, then the canonical model with its vendor
// prefix stripped, then the ordered pattern table, then nothing. The
// free-suffixed case is deliberate parity: neither the reference nor this port
// treats ":free" as a special case, so the model prices through its family
// pattern.
func TestPricing_FallbackChainOrder(t *testing.T) {
	cases := []struct {
		name       string
		provider   string
		model      string
		wantPriced bool
		wantInput  string
	}{
		{"provider override wins over canonical", "tokenrouter", "deepseek/deepseek-v3.2", true, "0.26"},
		{"canonical model beats the pattern table", "anything", "deepseek-chat", true, "0.14"},
		{"vendor-prefixed free-suffixed model resolves through its pattern", "th-1", "deepseek-v4.1-flash:free", true, "0.14"},
		{"case-insensitive pattern match", "anything", "DeepSeek-Chat", true, "0.14"},
		{"unpriced model answers not priced", "anything", "totally-unknown-model", false, ""},
		{"empty model answers not priced", "anything", "", false, ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			rates, priced := ResolvePricing(tc.provider, tc.model)
			if priced != tc.wantPriced {
				t.Fatalf("priced = %v, want %v", priced, tc.wantPriced)
			}
			if priced && rates.Input != tc.wantInput {
				t.Fatalf("input rate = %q, want %q", rates.Input, tc.wantInput)
			}
		})
	}
}

// TestPricing_CostFormula pins the token-to-cost conventions over a table: the
// inclusive-prompt split (cached and cache-creation are subsets, subtracted
// before the full input rate applies), the clamp when the subsets exceed the
// prompt, the reasoning premium on its own rate, the cached-rate fallback to
// the input rate, the exact 8-decimal rendering, and the zero answers for an
// empty report.
func TestPricing_CostFormula(t *testing.T) {
	rates := Rate{Input: "3", Output: "15", Cached: "0.3", CacheCreation: "3.75", Reasoning: "15"}

	cases := []struct {
		name   string
		tokens TokenCounts
		rate   Rate
		want   string
	}{
		{"prompt-inclusive cache split, no double-count", TokenCounts{Prompt: 330, Completion: 50, Cached: 200, CacheCreation: 30}, rates, "0.00122250"},
		{"subsets exceeding the prompt clamp to zero", TokenCounts{Prompt: 100, Cached: 80, CacheCreation: 40}, rates, "0.00017400"},
		{"plain pricing when no cache is present", TokenCounts{Prompt: 100, Completion: 50}, rates, "0.00105000"},
		{"reasoning tokens add their premium rate on top of output", TokenCounts{Completion: 100, Reasoning: 40}, rates, "0.00210000"},
		{"cached rate falls back to the input rate when absent", TokenCounts{Prompt: 100, Cached: 40}, Rate{Input: "3", Output: "15", Reasoning: "15"}, "0.00030000"},
		{"a billion input tokens at $5/M is $5000, exactly", TokenCounts{Prompt: 1000000000}, Rate{Input: "5", Output: "25"}, "5000.00000000"},
		{"an empty report answers the column scale", TokenCounts{}, rates, "0.00000000"},
		{"six-decimal rates render at the column scale", TokenCounts{Prompt: 1500000, Completion: 500000}, Rate{Input: "0.000003", Output: "0.000007"}, "0.00000800"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := CalculateCost(tc.tokens, tc.rate); got != tc.want {
				t.Fatalf("cost = %q, want %q", got, tc.want)
			}
		})
	}
}
