// Generates the capability corpus the Go port is pinned against.
//
// @file      tools/capability-gen.mjs
// @for       A committed JSON corpus of the reference's own capability answers,
//
//	one row per (provider, model) pair the embedded registry declares.
//
// @uses      node:fs, node:path, the reference checkout's
//
//	open-sse/providers/capabilities.js, and internal/registry/registry.yaml.
//
// @reason    internal/registry/capability.go is a port of the reference's
//
//	capability tables, and a port that is only checked against itself
//	proves nothing. This tool runs the reference's own
//	getCapabilitiesForModel over every model the port actually serves,
//	so TestCapabilities_MatchesTheReferenceCorpus compares the port to
//	the reference rather than to a second copy of the same guess.
//
//	It is a one-shot generator, not a build dependency: the JSON is
//	committed and the reference is not required to build app-serv. That
//	is deliberate, because the reference lives in a separate checkout
//	whose revision the corpus records.
//
// Usage:
//   node tools/capability-gen.mjs <reference-checkout> <output.json>
//
// The revision in the output is the checkout's HEAD at generation time. The
// embedded registry.yaml is pinned to 9router@db4499d, so a corpus generated
// from a newer checkout describes tables the registry's model ids were not
// chosen from; check the recorded revision before trusting a diff.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const [referenceRoot, outFile] = process.argv.slice(2);
if (!referenceRoot || !outFile) {
  console.error("usage: node tools/capability-gen.mjs <reference-checkout> <output.json>");
  process.exit(2);
}

const registryFile = path.resolve("internal/registry/registry.yaml");

// parseRegistry reads the two id levels this corpus needs: the provider id at
// two-space indent and each model id at six-space indent. A full YAML parser is
// avoided on purpose — the generator must run with no dependency install, and
// the file is machine-written by registry-gen.mjs so its shape is stable.
function parseRegistry(text) {
  const providers = [];
  let current = null;
  for (const line of text.split("\n")) {
    const provider = /^  - id: (.+)$/.exec(line);
    if (provider) {
      current = { id: provider[1].trim(), models: [] };
      providers.push(current);
      continue;
    }
    const model = /^      - id: (.+)$/.exec(line);
    if (model && current) {
      current.models.push(model[1].trim());
    }
  }
  return providers;
}

const capabilities = await import(
  pathToFileURL(path.join(referenceRoot, "open-sse/providers/capabilities.js")).href
);

const revision = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
  cwd: referenceRoot,
  encoding: "utf8",
}).trim();

const providers = parseRegistry(fs.readFileSync(registryFile, "utf8"));
const entries = [];
for (const provider of providers) {
  for (const model of provider.models) {
    const caps = capabilities.getCapabilitiesForModel(provider.id, model);
    entries.push({
      provider: provider.id,
      model,
      vision: caps.vision === true,
      tools: caps.tools === true,
      reasoning: caps.reasoning === true,
      thinking_format: caps.thinkingFormat || "",
      thinking_can_disable: caps.thinkingCanDisable !== false,
      thinking_range: caps.thinkingRange
        ? { min: caps.thinkingRange.min ?? null, max: caps.thinkingRange.max ?? null }
        : null,
      thinking_effort_supported: caps.thinkingEffortSupported === true,
    });
  }
}

entries.sort((a, b) =>
  a.provider === b.provider ? (a.model < b.model ? -1 : a.model > b.model ? 1 : 0) : a.provider < b.provider ? -1 : 1
);

const payload = {
  revision,
  source: "open-sse/providers/capabilities.js getCapabilitiesForModel",
  note: "Generated by tools/capability-gen.mjs; do not edit by hand.",
  entries,
};

fs.writeFileSync(outFile, JSON.stringify(payload, null, 2) + "\n");
const vision = entries.filter((e) => e.vision).length;
const tools = entries.filter((e) => e.tools).length;
const reasoning = entries.filter((e) => e.reasoning).length;
console.log(
  `${entries.length} entries from ${providers.length} providers at ${revision}: vision ${vision}, tools ${tools}, reasoning ${reasoning}`
);
