#!/usr/bin/env node
// Pricing table generator: reference pricing tables -> embedded JSON + oracle corpus.
//
// @file      tools/pricing-gen.mjs
// @for       Produces the embedded model-rate tables and the parity corpus from
//
//	the 9Router reference's own pricing module.
//
// @uses      node ESM import of the reference pricing module, node:fs,
//
//	node:child_process, node:path.
//
// @reason    SPEC-API-001 §7.12 states chat cost figures are estimates for
//
//	display, and the reference computes those estimates locally from
//	$-per-million-token rate tables with a three-step resolution chain.
//	A port that is only checked against itself proves nothing, so this
//	tool dumps the reference's tables verbatim (the embedded data) and
//	runs the reference's own resolver and cost function over every
//	(provider, model) pair the embedded registry declares plus fixed
//	token shapes (the corpus the Go tests compare against). Regenerate
//	after a reference bump with:
//	  node tools/pricing-gen.mjs <9router-checkout>
//
// @author    Dodi Rusmana <rusmanadodi@kentangtech.com>
// @layer     config
// @stability experimental
// @since     2026-09-23

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const [referenceRoot] = process.argv.slice(2);
if (!referenceRoot) {
  console.error("usage: node tools/pricing-gen.mjs <9router-checkout>");
  process.exit(2);
}

const tablesFile = path.resolve("internal/registry/pricing.json");
const corpusFile = path.resolve("internal/registry/testdata/pricing_corpus.json");
const registryFile = path.resolve("internal/registry/registry.yaml");

const pricing = await import(
  pathToFileURL(path.join(referenceRoot, "open-sse/providers/pricing.js")).href
);

const revision = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
  cwd: referenceRoot,
  encoding: "utf8",
}).trim();

// Rates cross the wire as decimal strings, never JSON numbers: the Go side
// parses them into exact rationals, and a float in between would already have
// lost the 6th decimal some rates carry.
const rate = (r, key) => (r && r[key] !== undefined ? String(r[key]) : null);

const model = Object.entries(pricing.MODEL_PRICING).map(([id, r]) => ({
  id,
  input: rate(r, "input"),
  output: rate(r, "output"),
  cached: rate(r, "cached"),
  reasoning: rate(r, "reasoning"),
  cache_creation: rate(r, "cache_creation"),
}));

const provider = Object.entries(pricing.PROVIDER_PRICING).flatMap(([pid, models]) =>
  Object.entries(models).map(([id, r]) => ({
    provider: pid,
    id,
    input: rate(r, "input"),
    output: rate(r, "output"),
    cached: rate(r, "cached"),
    reasoning: rate(r, "reasoning"),
    cache_creation: rate(r, "cache_creation"),
  }))
);

const pattern = pricing.PATTERN_PRICING.map((entry) => ({
  pattern: entry.pattern,
  input: rate(entry.pricing, "input"),
  output: rate(entry.pricing, "output"),
  cached: rate(entry.pricing, "cached"),
  reasoning: rate(entry.pricing, "reasoning"),
  cache_creation: rate(entry.pricing, "cache_creation"),
}));

fs.writeFileSync(
  tablesFile,
  JSON.stringify(
    {
      revision: `9router@${revision}`,
      source: "open-sse/providers/pricing.js",
      note: "Generated by tools/pricing-gen.mjs; do not edit by hand.",
      model,
      provider,
      pattern,
    },
    null,
    2
  ) + "\n"
);

// parseRegistry mirrors tools/capability-gen.mjs: the registry YAML is
// machine-written by registry-gen.mjs, so the two id levels are read by line
// shape rather than a YAML dependency.
function parseRegistry(text) {
  const providers = [];
  let current = null;
  for (const line of text.split("\n")) {
    const p = /^  - id: (.+)$/.exec(line);
    if (p) {
      current = { id: p[1].trim(), models: [] };
      providers.push(current);
      continue;
    }
    const m = /^      - id: (.+)$/.exec(line);
    if (m && current) current.models.push(m[1].trim());
  }
  return providers;
}

// The corpus token shapes: the live free-tier case, the reference's own
// cached-token test shape, a reasoning shape, and the zero/boundary shapes.
const shapes = [
  { name: "plain", tokens: { prompt_tokens: 65, completion_tokens: 68 } },
  {
    name: "cached",
    tokens: { prompt_tokens: 330, completion_tokens: 50, cached_tokens: 200, cache_creation_input_tokens: 30 },
  },
  {
    name: "reasoning",
    tokens: { prompt_tokens: 1000, completion_tokens: 200, cached_tokens: 100, reasoning_tokens: 80 },
  },
  { name: "input-only", tokens: { prompt_tokens: 1000000000 } },
  { name: "empty", tokens: { prompt_tokens: 0, completion_tokens: 0 } },
];

const providers = parseRegistry(fs.readFileSync(registryFile, "utf8"));
const entries = [];
for (const p of providers) {
  for (const modelID of p.models) {
    const resolved = pricing.getPricingForModel(p.id, modelID);
    const costs = {};
    if (resolved) {
      for (const shape of shapes) {
        costs[shape.name] = pricing.calculateCostFromTokens(shape.tokens, resolved).toFixed(8);
      }
    }
    entries.push({
      provider: p.id,
      model: modelID,
      rates: {
        input: rate(resolved, "input"),
        output: rate(resolved, "output"),
        cached: rate(resolved, "cached"),
        reasoning: rate(resolved, "reasoning"),
        cache_creation: rate(resolved, "cache_creation"),
      },
      costs,
    });
  }
}

entries.sort((a, b) =>
  a.provider === b.provider
    ? a.model < b.model
      ? -1
      : a.model > b.model
        ? 1
        : 0
    : a.provider < b.provider
      ? -1
      : 1
);

fs.writeFileSync(
  corpusFile,
  JSON.stringify(
    {
      revision,
      source: "open-sse/providers/pricing.js getPricingForModel + calculateCostFromTokens",
      note: "Generated by tools/pricing-gen.mjs; do not edit by hand.",
      shapes: shapes.map((s) => ({ name: s.name, tokens: s.tokens })),
      entries,
    },
    null,
    2
  ) + "\n"
);

const priced = entries.filter((e) => e.rates.input !== null).length;
console.log(
  `${model.length} model rates, ${provider.length} provider overrides, ${pattern.length} patterns at 9router@${revision}; ` +
    `corpus: ${entries.length} registry pairs, ${priced} priced`
);
